### ISSUE TITLE
Move to a GitHub org to continue maintenance?

### ISSUE THREAD

**Issue by josephholsten** [terra-farm/terraform-provider-virtualbox#10]
I almost certainly don't have the experience to maintain this myself, but I think we could move this repo to an org like [sous-chefs](http://github.com/sous-chefs) does for chef cookbooks. Then I can help out anyone wanting to contribute.

If that doesn't sound ideal, please let me know! I'd hate for this project to go unmaintained.

**Comment by josephholsten** [comment]
oh, I forgot to mention that discussion for the terra-farm org happens at https://github.com/terra-farm/meta/issues

**Comment by ccll** [comment]
@josephholsten Sure, seems a good idea, is it enough to add a link to 'sous-chefs' in the README.md? Please let me know.

**Comment by mrlesmithjr** [comment]
We should definitely keep the momentum of this project moving forward!!!

**Comment by magicalbob** [comment]
Is another option not to PR it in to hashicorp/terraform?

**Comment by ringods** [comment]
@magicalbob hashicorp no longer accepts PRs for new providers. The ones under the `terraform-providers` Github organization are the ones officially managed and released by Hashicorp. I just hope that Hashicorp soon gives us an easy way to get thirdparty providers downloaded & installed on a user system like they have with the supported ones.

**Comment by ringods** [comment]
@ccll could you arrange with @josephholsten to transfer ownership of this provider to the `terra-farm` organization?

@josephholsten once migrated, could you add me as a maintainer?

Context: [I need this provider](https://github.com/newcontext-oss/kitchen-terraform/issues/199#issuecomment-359865049) for local testing of my [XenServer](https://github.com/ringods/terraform-provider-xenserver) provider.

**Comment by ccll** [comment]
@ringods @josephholsten Hi guys, I'd really love to transfer the ownership, but I don't know how, could you tell me what should I do?

**Comment by ringods** [comment]
@ccll Here is the documentation on transferring a Github repo from a personal account to an organization account:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

So, I guess @josephholsten, @damacus or @rowleyaj should first give you `repo creation` access in the `terra-farm` organization before you can migrate the repo.

I'm no member of the `terra-farm` organization (yet).

**Comment by ringods** [comment]
@ccll @josephholsten @damacus @rowleyaj is there any update on this?

**Comment by ccll** [comment]
@rowleyaj @ringods Done! The repo has been successfully migrated to [terra-farm/terraform-provider-virtualbox](https://github.com/terra-farm/terraform-provider-virtualbox) under 'virtualbox' group, thanks for the help!

**Comment by ringods** [comment]
@rowleyaj could you have a look at my access in the `terra-farm/virtualbox` github team, or the rights for the team on that repo? It seems I only have READ access. I have a branch ready to update the sources and docs from `ccll` to `terra-farm` but I can't push.

<img width="1000" alt="screen shot 2018-03-10 at 10 40 42" src="https://user-images.githubusercontent.com/77923/37240738-c0c2a9a2-244f-11e8-86fd-aeb78318f327.png">

**Comment by rowleyaj** [comment]
@ringods this should be resolved now, message sent via team discussion to update on permissions structure.
