### ISSUE TITLE
Automated releases via Travis.

### ISSUE THREAD

**Issue by ringods** [terra-farm/terraform-provider-virtualbox#13]
The latest Github release of this provider is from 2015. Can we have Github releases automated for this provider? Here is the way to do it in Travis, when you tag a commit:

https://github.com/ringods/terraform-provider-xenserver/blob/master/.travis.yml#L34-L49

Hope this helps.

**Comment by CpuID** [comment]
It seems pyToshka's fork has been doing this, and has recent working releases.

https://github.com/pyToshka/terraform-provider-virtualbox/releases

**Comment by rowleyaj** [comment]
@ringods lets try reaching out to @pyToshka see if we can upstream those changes now that we've moved the repo to terra-farm. It could get confusing if we release those same version numbers but as different code.

@pyToshka may also be interesting in collaborating on the upstream repo now, looks like there are fairly recent changes in the fork.

**Comment by pyToshka** [comment]
@ringods yes, I can provide help with develop

**Comment by ringods** [comment]
@pyToshka to go forward, could you rebase your fork with what is on `master` of the repo on `terra-farm`, then submit a PR so we have all your changes included?

**Comment by ringods** [comment]
This is in place now with correct credentials to publish releases in this repository under the `terra-farm` umbrella.
