### ISSUE TITLE
Main imports the wrong provider package

### ISSUE THREAD

**Issue by sneal** [terra-farm/terraform-provider-virtualbox#17]
[line 8](https://github.com/ccll/terraform-provider-virtualbox/blob/master/main.go#L8) should be `"github.com/ccll/terraform-provider-virtualbox/provider"`

**Comment by ringods** [comment]
@sneal I'm [awaiting some more access rights](https://github.com/terra-farm/terraform-provider-virtualbox/issues/10#issuecomment-372017310) on this repo within the new `terra-farm` organization. Once in place, I can submit a branch I have ready locally updating everything to `github.com/terra-farm/terraform-provider-virtualbox`.

**Comment by VoyTechnology** [comment]
I believe this is done now @ringods  and can be closed?

**Comment by ringods** [comment]
Solved by #41
