### ISSUE TITLE
How to specify login credentials

### ISSUE THREAD

**Issue by mjbright** [terra-farm/terraform-provider-virtualbox#26]
It would be useful to document how to specify login credentials.

I've booted a couple of nodes using the example.tf but don't know how to specify login credentials or login with the example box.

I tried adding a connection construct within the resource without success.

Is this possible with this provider or are we obliged to prepare the box/image in advance with known credentials?

```
  connection {
      type     = "ssh"

      #user     = "root"
      #password = "${var.root_password}"

      user     = "ubuntu"
      password = "test1234"
      host_key = "${file("/home/mjb/.ssh/id_rsa.pub")}"
      public_key = "${file("/home/mjb/.ssh/id_rsa.pub")}"
  }
```

**Comment by ringods** [comment]
@mjbright most base boxes are built with Packer and use the standard Vagrant insecure ssh keypair. You can find the keypair here:

https://github.com/hashicorp/vagrant/tree/master/keys

**Comment by mjbright** [comment]
Thanks for the info, I didn't know about that keypair.

After a few unsuccessful attempts (logging in as root or ubuntu) I realized
I should try vagrant user.

I think it's worth documenting that insecure keypair and how to use it.

Would be nice to be able to provide another keypair of course.

Anyway, I've got what I needed thanks a lot!

**Comment by zBrainiac** [comment]
Hi all
first of all I like to thanks you very much for all the work you do! Is in the meantime a updated documentation available?

**Comment by jaredbrogan** [comment]
+1 on this request

**Comment by VoyTechnology** [comment]
Looking back, it does seem like the comment was added about the insecure key - https://github.com/terra-farm/terraform-provider-virtualbox/commit/1d963062fe46314fa5e414fd2aa4daa9245da563.

Seeing how the use of provisioners is now discouraged, I don't think adding more documentation on how to establish a SSH connection is necessary.
