### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by regentoop** [terra-farm/terraform-provider-virtualbox#48]
Hello I hope this is the right place to put this. I found the installation instructions in the readme incomplete. I think they should be expanded a bit. 
I am working on a windows 10 device with terraform, vagrant, virtualbox and go installed. After running the go get instruction in the readme(go get github.com/terra-farm/terraform-provider-virtualbox), I had to copy the binary from the $GO_HOME/bin folder to the following location "C:\Users\_$(whoami)_\AppData\Roaming\terraform.d\plugins\windows_amd64" _(please note to replace the $(whoami) variable with the appropriate username)_ before terraform could recognize the provider.

**Comment by ringods** [comment]
@regentoop I would like to bring the providers under the `terra-farm` umbrella ASAP to the upcoming Terraform 0.12. This version will bring automatic download of providers shortly after that. See this:

https://github.com/hashicorp/terraform/issues/15252#issuecomment-444128463

**Comment by darkdrgn2k** [comment]
even with that i keep getting

```
Error: Error asking for user input: 1 error(s) occurred:

* provider.virtualbox: plugin exited before we could connect
```

any idea what im doing wrong?

is the file name `terraform-provider-virtualbox.exe` or `terraform-provider-virtualbox_windows_amd64.exe`

**Comment by darkdrgn2k** [comment]
never mind duplicate issue -  #31

**Comment by VoyTechnology** [comment]
I am not sure was the issue created before or after the change in the README, but it is included in step 4:
> 4. mv terraform-provider-virtualbox examples/

Closing the issue.

Ps. It could be easily checked when the change was made but effort :)

**Comment by ringods** [comment]
General installation instructions for all the providers of the terra-farm community can be found here:

https://terra-farm.github.io/main/installation.html

It is assumed that, as a user, you download the provider from the [Github releases](https://github.com/terra-farm/terraform-provider-virtualbox/releases) page. Building from source is more when you want to contribute to the evolution of this provider.
