### ISSUE TITLE
Listing on Terraform's site

### ISSUE THREAD

**Issue by mrjcleaver** [terra-farm/terraform-provider-virtualbox#5]
Is there a reason this is not listed on https://www.terraform.io/docs/providers/index.html ?

**Comment by ccll** [comment]
This project is not mature enough and sadly I don't have the time to maintain it. Better find someone to take over it.

**Comment by VoyTechnology** [comment]
Most likely it will stay under the `terra-farm` umbrella - I am not sure are there any commercial users of the provider, and most likely it will be always community supported (if at all). The best we can hope for is ability to pull third party providers though terraform registry, as outlined in https://github.com/hashicorp/terraform/issues/15252, and that would make me personally happy. I will close this issue as there is nothing we can do about it, and as @ccll said 2.5 years ago, this project is not mature enough, but we are trying!
