### ISSUE TITLE
import go-virtualbox

### ISSUE THREAD

**Issue by catay** [terra-farm/terraform-provider-virtualbox#54]
Hi,

Is there a reason why the provider imports 'github.com/pyToshka/go-virtualbox'  and not 'github.com/terra-farm/go-virtualbox'  ?   
The latest seems to be maintained and also contains a proper license. 

Happy to submit a PR to get that changed if that makes sense.

Cheers.

**Comment by VoyTechnology** [comment]
It was left out a [long time ago][1] and forgotten about. I don't think there is any reason why not to use it. I was planning a long time ago to rewrite the package to talk directly using Virtualbox SDK, but the Go API would stay the same (or at least be semver'ed). So feel free to create a PR.

[1]: https://github.com/terra-farm/terraform-provider-virtualbox/pull/30#discussion_r201232640

**Comment by ringods** [comment]
@VoyTechnology I'm not in favor of using the Virtualbox SDK. The SDK is COM based, which is old technology and not very easy to find documentation for. I'm also not sure if this works equally wel on all platforms. Personally, I'm more in favor of improving the integration via `VBoxManage`. However, let's discuss that in the `go-virtualbox` issue tracker. ;-)

**Comment by VoyTechnology** [comment]
Resolved by #55
