### ISSUE TITLE
Fix the build for Mac on Travis

### ISSUE THREAD

**Issue by ringods** [terra-farm/terraform-provider-virtualbox#65]
I changed the build setup a bit, but it seems that fetching some of the Go dependencies on Mac seems to fail now. Needs further investigation.

Example failure:
https://travis-ci.org/terra-farm/terraform-provider-virtualbox/jobs/566687490

**Comment by VoyTechnology** [comment]
Not sure would we want to migrate to Github Actions, but it is possible they might include MacOS support:

 https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions

**Comment by VoyTechnology** [comment]
Actions are now GA, so we can take a look. Might also help us with #83

**Comment by ringods** [comment]
MacOS build is running via Github Actions.
