### ISSUE TITLE
Issues running terraform v0.12.6 init on ubuntu

### ISSUE THREAD

**Issue by nbonavia** [terra-farm/terraform-provider-virtualbox#66]
Hi, I have downloaded the latest plugin binary from https://github.com/terra-farm/terraform-provider-virtualbox/releases/download/v0.2.0/terraform-provider-virtualbox-v0.2.0-linux_amd64 and placed it in ~/.terraform.d/plugins/linux_amd64 and created a sample main.tf as explained in https://blog.opennix.ru/posts/use_terraform_with_virtualbox/

Unfortunately when I ran 'terraform init' in the folder, I got the below error: -
```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "virtualbox" not available for installation.

A provider named "virtualbox" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name
```

Can anyone suggest a way how to make this work?
Thanks

**Comment by ringods** [comment]
@nbonavia did you rename the provider executable? It should follow a specific pattern which can be read in the last paragraph of the installation notes:

https://terra-farm.github.io/main/installation.html

**Comment by nbonavia** [comment]
Yes it worked, I renamed the file to 'terraform-provider-virtualbox' and placed it in folder ~/.terraform.d/plugins/linux_amd64

Thank you for your help
