### ISSUE TITLE
Virtual machine can not boot after create by teraform

### ISSUE THREAD

**Issue by chithanh89** [terra-farm/terraform-provider-virtualbox#76]
HI Guys,

I'm new of Teraform, i use example config to run create virtual machine in virtualbox.
The machine created but can't boot to OS.
Error on Teraform cli:
Error: Error applying plan:

1 error(s) occurred:

* virtualbox_vm.node: 1 error(s) occurred:

* virtualbox_vm.node: [ERROR] Wait VM until ready: waiting for VM (node-01) to become ready: timeout while waiting for state to become 'yes' (timeout: 5m0s)

And error on virtualbox:
FATAL: Could not read from the boot medium! System halted
Where 're my missing? My virtualbox version 6.0 and Tera version 0.11.13

**Comment by ringods** [comment]
Can you please post user question on our chat channel?

https://gitter.im/terra-farm/terraform-provider-virtualbox

The issue tracker is to report bugs and file new feature requests.
