### ISSUE TITLE
add support for a cloud init disk

### ISSUE THREAD

**Issue by rgl** [terra-farm/terraform-provider-virtualbox#78]
It would be nice to have a way to create a cloud init disk, e.g., a `virtualbox_cloudinit_disk` resource, that would work alike [libvirt_cloudinit_disk](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/cloudinit.html.markdown)

**Comment by VoyTechnology** [comment]
I am going to close it in favour of #49, since we already plan on adding disks as its own resource. The provider already has support for providing `user_data`: https://github.com/terra-farm/terraform-provider-virtualbox/blob/master/virtualbox/resource_vm.go#L89 (but I'm not 100% does it work ATM).
