### ISSUE TITLE
Terraform v0.7.7  support?

### ISSUE THREAD

**Issue by nemonik** [terra-farm/terraform-provider-virtualbox#8]
W/ Terraform v0.7.7 installed and lasted compiled executable.

➜  terraform-test terraform plan  
Error configuring: 1 error(s) occurred:
- Unrecognized remote plugin message: 2|unix|/var/folders/4z/vg3f9q9n35v96126f23b6dz8lzdwds/T/tf-plugin326334445

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

**Comment by edify42** [comment]
I had a similar issue. Trying to recompile from source but I'm getting an issue with a reference to a code.google project.

**Comment by ccll** [comment]
I've been really busy lately, so patches are welcomed!

**Comment by pyToshka** [comment]
This provider are work. I'm testing with Terraform v0.9.5

**Comment by pyToshka** [comment]
@nemonik Now you can use for latests version terraform

**Comment by ccll** [comment]
Since I merged @py

**Comment by ringods** [comment]
Fixed by a73af7c. We build against Terraform 0.11.7.
