### ISSUE TITLE
terraform does not recognizes the plugin

### ISSUE THREAD

**Issue by silent-mobius** [terra-farm/terraform-provider-virtualbox#88]
Hello 
I followed the contribution guide to build from the sources the plugin as follows:
```sh
    git clone https://github.com/terra-farm/terraform-provider-virtualbox
    cd terraform-provider-virtualbox
    go build
    mv terraform-provider-virtualbox examples/
    cd examples/
    terraform init
    terraform plan
    terraform apply
```
 i used the temlpate for terraform file, provided at the same guide to `plan` and `apply` the template, yet i am getting next error:
```sh
Error: Could not satisfy plugin requirements
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".
Error: provider.virtualbox: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
```
could any one help me out ?
P.S i am using Terraform v0.12.19

**Comment by ringods** [comment]
Why are you building from source? The published docs describe how to download a pre-built provider binary and where to install it locally on your system to run. Have you followed links which are in the README file?

https://github.com/terra-farm/terraform-provider-virtualbox/blob/master/README.md

**Comment by silent-mobius** [comment]
actually I did - it lead to terra-farm site which does not has anything on it - i was able to build from source and make it work but now i am playing charades with main.tf file because i am missing documentation, which i asked politely to give a hand and help with  in other issue.

**Comment by ringods** [comment]
The site can definitely be organized better, but the flow is this:
* go to the virtualbox provider [releases](https://github.com/terra-farm/terraform-provider-virtualbox/releases/tag/v0.2.0)
* download the binary for your platform
* read the [installation instructions](https://terra-farm.github.io/main/installation.html) for the binary which are on the site.
* see the [usage docs](https://terra-farm.github.io/provider-virtualbox/reference/resource_vm.html) of the single `vm` resource available in the provider

**Comment by silent-mobius** [comment]
why not to put these instructions on main page ?

**Comment by ringods** [comment]
All of that will be superseded soon when we can publish the providers in the Terraform Registry:

https://www.hashicorp.com/blog/announcing-providers-in-the-new-terraform-registry/
