### ISSUE TITLE
Publish on Terraform Registry for upcoming TF 0.13

### ISSUE THREAD

**Issue by ringods** [terra-farm/terraform-provider-virtualbox#90]
We should prepare to get this provider published on the Terraform Registry.

https://github.com/hashicorp/terraform/issues/25016

@carlpett I noticed you enrolled the `sops` provider in the TF 0.13 beta program. Can you enlighten us how we can get this and the other TF providers in the [`terra-farm`](https://github.com/terra-farm) organization in this beta program too?

**Comment by carlpett** [comment]
Hi @ringods,
I believe the sign-up at this point is basically an email to terraform-registry-beta@hashicorp.com. I got contacted by them because I've been asking them about this for a year or two..

**Comment by ringods** [comment]
@carlpett thank you for the reach out and the email address. I'll get in touch with them right away.

**Comment by mjbright** [comment]
Any progress on this?

**Comment by mjbright** [comment]
In the meantime is there a workaround for this?

I came back to this provider for the first time in a while and am getting this same error when using the examples/example.tf with either 0.13 or an older 0.12 (0.12.24).

**Comment by VoyTechnology** [comment]
We might have to create a draft `v0.2.1` to verify the changes after #93 and #94 are merged. The GPG key ownership also has to be discussed that is required for publishing the provider. There are also a few other small things we will probably need, like a `website/` in the root for documentation, as suggested by https://github.com/hashicorp/terraform-provider-scaffolding

**Comment by ringods** [comment]
@VoyTechnology I suggest you use your GPG key as you originated the project and still do most of the work. Credits go mainly to you.

Let's first convert the documentation back to Markdown in the structure that is required for publishing on the registry. After that, we can try with some 0.2.x releases to get the release management in place.

**Comment by VoyTechnology** [comment]
#96 adds the website. I think we should keep the old documentation up for the time being, until we have the provider published, and then on the website we can link to the Terraform Registry Documentation.

**Comment by ringods** [comment]
@VoyTechnology for you to be able start testing the publishing to the Registry, can you follow the instructions listed in the docs to get your GPG key installed?

https://www.terraform.io/docs/registry/providers/publishing.html#organizations

**Comment by VoyTechnology** [comment]
Sorry this took so long, been hanging on the bottom of my TODO list. While not finished, I have generated the PGP key, added it to Github Action Secrets, and sent an email to Hashicorp to get the PGP Key added. I am just waiting for response, and then we should be able to tag a release and see did it work.

**Comment by emo3** [comment]
I still have to use v12, because v13+ requires this functionality.

**Comment by VoyTechnology** [comment]
@emo3 Unfortunately I am not the owner of the `terra-farm` organization, and as admins, only they can upload the required GPG key. I have posted it in the internal discussion but I am awaiting the response. Can you help me our @ringods?

**Comment by ringods** [comment]
@VoyTechnology willing to help you out here. Do you required ownership of the `terra-farm` organization on Github, on the TF Registry or on both?

**Comment by VoyTechnology** [comment]
@ringods I think if I have permissions ownership  for GitHub Org it will automatically add me on Terraform Registry.

**Comment by VoyTechnology** [comment]
I looked today, and somehow the PGP key was there on the Registry website, I have created `v0.2.1-alpha` Draft release to test does it work, and the CI did create the needed binaries, but apparently the signatures for binaries are not valid - https://registry.terraform.io/providers/terra-farm/virtualbox

I probably messed something up with the PGP keys (I learned that I really dislike PGP in the process).

**Comment by ringods** [comment]
@VoyTechnology I doubt that the group management on Github is taken over by the Hashicorp Registry, so admin level on GH will probably not give you admin on the Registry.

For the `terra-farm` organization on Registry, we have a single PGP key registered with ID `DDBA1674AA3EA0EE`. Can you check if this matches one of your keys?

**Comment by VoyTechnology** [comment]
I think that key is only used for the [xenorchestra](https://registry.terraform.io/providers/terra-farm/xenorchestra/latest) provider.

The publishing document https://www.terraform.io/docs/registry/providers/publishing.html#preparing-and-adding-a-signing-key states that (relevant portion made bold):

> The ASCII-armored public key to the Terraform Registry by going to User Settings > Signing Keys. You can add keys for your personal namespace, __or any organization which you are an admin of.__

When I try to add the key, the `terra-farm` namespace is not available.

I guess if making me an org admin is not not possible, perhaps someone who has control over the registered key `DDBA1674AA3EA0EE ` can replace the secrets in Github Actions instead? Or create and add a new key?

**Comment by ringods** [comment]
@VoyTechnology the Github organization is managed by the Terraform code in this repo:

https://github.com/terra-farm/terraform-github-org

In the last commits, you can see that I made you an owner of the `terra-farm` Github organization. Can you check if the ownership level on the Github organization also provides you ownership of the `terra-farm` namespace on the Terraform Registry?

Also, Hashicorp provides us with a free Terraform Cloud account. You should have received an invite as well on your GMail address.

**Comment by VoyTechnology** [comment]
# SUCCESS!!! 🥳 🚀 

## https://registry.terraform.io/providers/terra-farm/virtualbox/

The organisation had Terraform Registry permissions disabled. I had to look around the settings to make it work. After granting the permission I was able to finally add the GPG key, and Terraform verified the signature.

**Comment by emo3** [comment]
Error: [ERROR] Setup VM properties: exit status 1
│ 
│   with virtualbox_vm.node[0],
│   on node.tf line 1, in resource "virtualbox_vm" "node":
│    1: resource "virtualbox_vm" "node" {
Here is my node.tf file:
resource "virtualbox_vm" "node" {
  count     = 1
  name      = "node-1"
  image     = "https://app.vagrantup.com/generic/boxes/centos8/versions/3.2.24/providers/virtualbox.box"
  cpus      = 1
  memory    = "1024 mib"
  network_adapter {
    type           = "hostonly"
    host_interface = "vboxnet1"
  }
}
output "IPAddr" {
  value = element(virtualbox_vm.node.*.network_adapter.0.ipv4_address, 1)
}
Here are my versions.tf file:
terraform {
  required_providers {
    virtualbox = {
      source = "terra-farm/virtualbox"
      version = "0.2.1-alpha.1"
    }
  }
}

I do not see what I am doing wrong.
