### ISSUE TITLE
Consider Disabling Travis CI

### ISSUE THREAD

**Issue by VoyTechnology** [terra-farm/terraform-provider-virtualbox#95]
Now that Github Actions is setup, we might consider removing Travis CI. Github Actions has a tighter integration with Github, is also free, and it seems to work a bit faster than Travis.

**Comment by ringods** [comment]
Travis CI integration should be fully removed. For the open PR #82 to pick up Github Actions, it needs to be rebased. The current "checks" still stem from before Github Actions were introduced.
